stages:
  - build
  - deploy

build_prod_image:
  stage: build

  before_script:
    - sudo podman login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY_URL

  script:
    - sudo echo "Test build"

  after_script:
    - sudo echo "Test after"

  except:
    changes:
      - .gitlab-ci.yml

  only:
    - master


run_container:
  stage: deploy

  before_script:
    - sudo podman login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY_URL
    - sudo podman stop $CONTAINER_NAME || echo "Container doesn't started"
    - sudo podman rm $CONTAINER_NAME || echo "Coniner doesn't exist"
    - sudo podman rmi $IMAGE_NAME:latest || echo "Image doesn't exist"
    - sudo podman pull $IMAGE_NAME:latest

  script:
    - sudo podman run -d -v postgres-run:/var/run/postgresql --name=$CONTAINER_NAME --pod=$POD_NAME $IMAGE_NAME:latest

  except:
    changes:
      - .gitlab-ci.yml

  only:
    - master
