stages:
  - build
  - deploy
  - update

build_prod_image:
  stage: build
  when: manual

  before_script:
    - source source.env
    - sudo podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - sudo buildah bud --no-cache -f Dockerfiles/Dockerfile -t $CI_REGISTRY_IMAGE/$POSTGRES_IMAGE:build .

  after_script:
    - source source.env
    - echo "Test after"
    - sudo podman push $CI_REGISTRY_IMAGE/$POSTGRES_IMAGE:build
    - sudo podman rmi $(sudo podman images | grep '<none>' | awk '{ print $3}')

  only:
    - master


deploy_oracle_fdw_grafana_container:
  stage: deploy
  when: manual
  before_script:
    - source source.env
    - sudo podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - sudo podman stop $CONTAINER_NAME || echo "Container doesn't started"
    - sudo podman rm $CONTAINER_NAME || echo "Coniner doesn't exist"
    - sudo podman rmi $CI_REGISTRY_IMAGE/$POSTGRES_IMAGE:latest || echo "Image doesn't exist"
    - sudo podman tag $CI_REGISTRY_IMAGE/$POSTGRES_IMAGE:build $CI_REGISTRY_IMAGE/$POSTGRES_IMAGE:latest
    - sudo podman rmi $CI_REGISTRY_IMAGE/$POSTGRES_IMAGE:build

  script:
    - |
      sudo podman run -d --name=$CONTAINER_NAME --pod=$POD_NAME \
      -e POSTGRES_PORT_FOR_ENV=5432 \
      -e POSTGRES_USER=$POSTGRES_USER \
      -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
      -e POSTGRES_DB=$POSTGRES_DB \
      $CI_REGISTRY_IMAGE/$POSTGRES_IMAGE:latest

  except:
    changes:
      - .gitlab-ci.yml

  only:
    - master


update_nglm_oracle:
  stage: update
  environment:
    name: slomap1
    url: https://grafana.nglm.rt.ru
  before_script:
    - source source.env
    - envsubst < init-scripts/fdw_oracle_create.sql > tmp.sql
    - sudo podman exec -i $CONTAINER_NAME psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --no-password --dbname $POSTGRES_DB < tmp.sql
  script:
    - date

  only:
    - master

update_ge_oracle:
  stage: update
  environment:
    name: spvprod
    url: https://grafana.nglm.rt.ru
  before_script:
    - source source.env
    - source $spvprod
    - envsubst < init-scripts/fdw_oracle_create.sql > tmp.sql
    - sudo podman exec -i $CONTAINER_NAME psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --no-password --dbname $POSTGRES_DB < tmp.sql

  script:
    - date

  only:
    - master